"use client";

import { useState } from "react";
import { Upload, FileText, Loader2 } from "lucide-react";
import api from "@/services/api";
import { AnalysisResponse } from "@/types";

// explains shape of props passed to this component
interface ResumeUploadProps {
  onSuccess: (data: any) => void;
}

export default function ResumeUpload({
  onSuccess,
}: ResumeUploadProps) {
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleFileChange = (
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    const selectedFile = e.target.files?.[0];

    if (!selectedFile) return;

    if (selectedFile.type !== "application/pdf") {
      setError("Please upload a PDF file.");
      return;
    }

    setError("");
    setFile(selectedFile);
  };

  const handleUpload = async () => {
    if (!file) {
      setError("Please select a resume.");
      return;
    }

    try {
      setLoading(true);
      setError("");

      const formData = new FormData();

      formData.append("file", file);

      const response = await api.post(
        "/recommend-pdf",
        formData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );

      onSuccess(response.data);
    } catch (err) {
      console.error(err);

      setError(
        "Failed to analyze resume. Please try again."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
  <div className="relative w-full max-w-2xl overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 p-8 shadow-[0_25px_80px_rgba(0,0,0,0.45)] backdrop-blur-xl">
    {/* Background Glow */}
    <div className="absolute -left-20 -top-20 h-56 w-56 rounded-full bg-blue-500/20 blur-3xl" />
    <div className="absolute -bottom-20 -right-20 h-56 w-56 rounded-full bg-violet-500/20 blur-3xl" />

    <div className="relative z-10">
      <div className="mb-8 text-center">
        <div className="mb-3 inline-flex items-center rounded-full border border-blue-500/20 bg-blue-500/10 px-4 py-1 text-sm font-medium text-blue-300">
          AI Career Intelligence
        </div>

        <h2 className="text-4xl font-bold tracking-tight text-white">
          Analyze Your Resume
        </h2>

        <p className="mt-3 text-slate-400">
          Upload your resume and receive personalized career insights,
          skill gap analysis, job role recommendations, salary prediction,  
          and career roadmap generated by our machine learning engine.
        </p>
      </div>

      <label
        htmlFor="resume"
        className="group flex cursor-pointer flex-col items-center justify-center rounded-2xl border border-white/10 bg-white/[0.03] p-12 transition-all duration-300 hover:border-blue-500/40 hover:bg-white/[0.05] hover:shadow-[0_0_40px_rgba(59,130,246,0.15)]"
      >
        <div className="mb-5 rounded-2xl bg-gradient-to-br from-blue-500 to-violet-600 p-4 shadow-lg shadow-blue-500/20 transition-transform duration-300 group-hover:scale-105">
          <Upload className="h-8 w-8 text-white" />
        </div>

        <p className="text-lg font-semibold text-white">
          Upload Resume
        </p>

        <p className="mt-1 text-sm text-slate-400">
          Drag & drop your PDF or click to browse
        </p>

        <p className="mt-2 text-xs uppercase tracking-widest text-slate-500">
          PDF ONLY
        </p>

        <input
          id="resume"
          type="file"
          accept=".pdf"
          className="hidden"
          onChange={handleFileChange}
        />
      </label>

      {file && (
        <div className="mt-5 flex items-center gap-3 rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-4">
          <div className="rounded-lg bg-emerald-500/20 p-2">
            <FileText className="h-5 w-5 text-emerald-400" />
          </div>

          <div className="min-w-0">
            <p className="text-sm font-medium text-white">
              Resume Selected
            </p>

            <p className="truncate text-sm text-slate-300">
              {file.name}
            </p>
          </div>
        </div>
      )}

      {error && (
        <div className="mt-4 rounded-xl border border-red-500/20 bg-red-500/10 p-3">
          <p className="text-sm text-red-400">
            {error}
          </p>
        </div>
      )}

      <button
        onClick={handleUpload}
        disabled={loading}
        className="mt-8 flex w-full items-center justify-center rounded-2xl bg-gradient-to-r from-blue-600 via-blue-500 to-violet-600 py-4 font-semibold text-white shadow-lg shadow-blue-500/20 transition-all duration-300 hover:scale-[1.02] hover:shadow-blue-500/40 disabled:cursor-not-allowed disabled:opacity-60"
      >
        {loading ? (
          <>
            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
            Analyzing Resume...
          </>
        ) : (
          "Generate Career Insights"
        )}
      </button>

      <div className="mt-6 flex items-center justify-center gap-6 text-xs text-slate-500">
        <span>AI Skill Analysis</span>
        <span>•</span>
        <span>Career Recommendations</span>
        <span>•</span>
        <span>Growth Roadmap</span>
      </div>
    </div>
  </div>
);
}